openapi: 3.0.3
info:
  version: 1.0.1
  title: Homework 4
  description: |-
    Documentation for Homework 4. ML prediction for student success for applications.
servers:
  - url: http://127.0.0.1:5000
tags:
  - name: Predict
    description: endpoint for prediction

paths:
  /predict:
    get:
      tags:
        - Predict
      summary: Student success prediction
      description: Predict which applicants are more likely to succeed. Parameters likely to change
      operationId: predict
      parameters:
        - name: G1
          in: query
          description: first period grade (from 0 to 20)
          required: true
          schema:
            type: integer
        - name: G2
          in: query
          description: second period grade (from 0 to 20)
          required: true
          schema:
            type: integer
        - name: absences
          in: query
          description: number of school absences (from 0 to 93)
          required: true
          schema:
            type: integer
      responses:
            '200':
              description: OK
            '500':
              description: Invalid input (missing value or out of range)
